const REAL={
  maos:{name:'Cueva de las Manos — Argentina',img:'https://thumb.wikimedia.org/wikipedia/commons/thumb/7/72/Cueva_de_las_Manos_%286811931046%29.jpg/960px-Cueva_de_las_Manos_%286811931046%29.jpg',page:'https://commons.wikimedia.org/wiki/File:Cueva_de_las_Manos_(6811931046).jpg',credit:'Pablo A. Gimenez • CC BY-SA 2.0'},
  lascaux:{name:'Lascaux — França',img:'https://upload.wikimedia.org/wikipedia/commons/0/07/Lascaux2.jpg',page:'https://commons.wikimedia.org/wiki/File:Lascaux2.jpg',credit:'Wikimedia Commons • domínio público / reprodução de obra em domínio público'},
  serra:{name:'Serra da Capivara — Brasil',img:'https://thumb.wikimedia.org/wikipedia/commons/thumb/7/79/Serra_da_Capivara_-_Painting_6.JPG/960px-Serra_da_Capivara_-_Painting_6.JPG',page:'https://commons.wikimedia.org/wiki/File:Serra_da_Capivara_-_Painting_6.JPG',credit:'Vitor 1234 • CC BY-SA 3.0'},
  altamira:{name:'Altamira — Espanha',img:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Altamira,_bison.jpg?width=960',page:'https://commons.wikimedia.org/wiki/File:Altamira,_bison.jpg',credit:'Wikimedia Commons • reprodução em domínio público'}
};

const E=(id,icon,title,period,intro,tech,analysis,meaning,ref,q,opts,correct)=>({id,icon,title,period,intro,tech,analysis,meaning,ref,q,opts,correct});
const scenes=[
 {id:'entrada',title:'Entrada da Caverna',image:'assets/scenes_v9/01_entrada.jpg',sound:'vento e eco distante',e:[
  E('e1','🖐️','Mãos em negativo','Arte rupestre — estêncil','A mão apoiada sobre a rocha funciona como máscara. O pigmento pulverizado em torno dos dedos e da palma produz um contorno negativo, uma técnica documentada em diferentes tradições rupestres.','Técnica: estêncil por sopro/pulverização|Pigmento provável: ocre vermelho rico em óxidos de ferro|Suporte: parede rochosa relativamente lisa|Conservação: sensível a umidade, sais e contato humano','A análise arqueológica considera cor, granulometria do pigmento, superposição, dimensão das mãos, posição no painel e associação com outros motivos. O significado não é diretamente recuperável: identidade, rito, memória e marcação de presença são hipóteses possíveis, não certezas.','Mostra que o corpo humano também podia participar diretamente do processo técnico de produção da imagem, transformando um gesto simples em registro durável.',REAL.maos,'O que caracteriza um estêncil de mão?',['Pigmento aplicado ao redor da mão','Incisão profunda feita com metal','Impressão em argila cozida'],0),
  E('e2','🦬','Grande bovídeo','Paleolítico Superior','Grandes mamíferos aparecem com frequência em repertórios paleolíticos, muitas vezes com destaque de escala e posição. Contornos dorsais, chifres e massa corporal ajudam a reconhecer o animal.','Técnica: contorno + preenchimento parcial|Pigmentos: carvão, manganês e ocres ferruginosos|Recurso plástico: relevo natural da parede|Composição: figura dominante no painel','O tamanho da figura pode criar hierarquia visual. A arqueologia compara traços, sobreposições e escolha do suporte para entender sequências de execução, mas evita reduzir toda representação animal a “cena de caça”.','Ajuda a discutir observação da fauna, seleção temática e organização simbólica do espaço cavernícola.',REAL.altamira,'Que recurso pode aumentar a sensação de volume?',['Aproveitar saliências naturais da rocha','Aplicar verniz sintético','Usar perspectiva fotográfica moderna'],0)
 ]},
 {id:'corredor',title:'Corredor dos Vestígios',image:'assets/scenes_v9/02_corredor.jpg',sound:'gotejamento e passos abafados',e:[
  E('e3','🔴','Pontos e manchas pigmentares','Sinais não figurativos','Conjuntos de pontos, manchas e pequenas marcas podem fazer parte de sistemas gráficos tão relevantes quanto animais e figuras humanas.','Técnica: toque digital, pincelamento ou aplicação pontual|Pigmento: hematita moída e aglutinantes naturais|Distribuição: sequências repetidas|Registro: posição e espaçamento são medidos','Pontos não devem ser tratados automaticamente como “contagem” ou “calendário”. O método correto é descrever padrão, frequência, associação e contexto estratigráfico antes de propor interpretação.','Mostra que a comunicação visual pré-histórica incluía repertórios abstratos e repetitivos.',REAL.maos,'Qual é a conduta científica diante de pontos abstratos?',['Descrever e comparar antes de interpretar','Assumir que são números','Ignorar por não serem animais'],0),
  E('e4','🦌','Cervídeo em perfil','Motivo zoomórfico','A representação em perfil facilita a leitura da espécie, principalmente quando galhadas, pescoço e linha dorsal aparecem destacados.','Técnica: traço linear e preenchimento parcial|Pigmento: carvão e ocre|Postura: perfil lateral|Indicador anatômico: galhadas ramificadas','A identificação taxonômica deve ser prudente. Forma das galhadas, proporção corporal e contexto regional ajudam a diferenciar cervídeos de outros ungulados.','Permite relacionar arte, ambiente, fauna e conhecimento visual acumulado pelos grupos humanos.',REAL.lascaux,'Qual detalhe ajuda a reconhecer cervídeos?',['Galhadas ramificadas','Nadadeiras','Bico curvo'],0)
 ]},
 {id:'maos',title:'Galeria das Mãos',image:'assets/scenes_v9/03_maos.jpg',sound:'eco fechado e gotejamento',e:[
  E('e5','🖐️','Painel coletivo de mãos','Marcadores corporais','A repetição de mãos de diferentes tamanhos, cores e posições pode indicar uso prolongado do painel e participação de diversos indivíduos.','Procedimento: estêncil negativo|Variação: tamanhos, cores e orientação|Estratigrafia visual: superposição de camadas|Registro: fotogrametria e mapeamento digital','Em painéis densos, a superposição permite discutir sequência relativa de execução. Diferenças de pigmento e posição podem apontar eventos distintos, embora a datação absoluta nem sempre seja possível.','Ajuda a compreender a caverna como espaço reutilizado e socialmente significativo ao longo do tempo.',REAL.maos,'O que a superposição de várias mãos pode sugerir?',['Uso repetido do painel','Uma única pintura instantânea','Uso de impressão mecânica'],0),
  E('e6','🏹','Figura humana esquemática','Antropomorfo','Corpos lineares, membros alongados e instrumentos simples privilegiam ação e gesto em vez de anatomia realista.','Técnica: traço fino e silhueta|Anatomia: simplificação intencional|Associação: humanos próximos a animais|Leitura: postura e direção do movimento','O arqueólogo observa posição dos braços, direção do corpo, instrumentos e relação espacial entre personagens. A mesma forma pode participar de caça, dança, deslocamento ou outra ação.','Mostra como narrativas visuais podem ser construídas com poucos traços e forte ênfase no movimento.',REAL.serra,'O que costuma ser mais importante nessas figuras?',['O gesto e a ação','O retrato facial detalhado','A perspectiva renascentista'],0)
 ]},
 {id:'passagem',title:'Passagem Estreita',image:'assets/scenes_v9/04_passagem.jpg',sound:'eco curto e água próxima',e:[
  E('e7','〰️','Zigue-zagues e linhas','Sinais geométricos','Linhas paralelas, zigue-zagues e padrões repetidos aparecem em diferentes conjuntos rupestres. Eles podem estar associados a animais, mãos ou figuras humanas.','Técnica: traço contínuo|Forma: repetição geométrica|Pigmento: ocre ou carvão|Análise: frequência, posição e associação','A interpretação de sinais geométricos é especialmente delicada. Sem contexto adicional, não é adequado afirmar que representam água, caminhos, escrita ou calendários.','Ajuda a mostrar que a arte rupestre não é apenas figurativa: padrões abstratos fazem parte do repertório visual.',REAL.maos,'Como interpretar um zigue-zague isolado?',['Com cautela, considerando o contexto','Como escrita alfabética comprovada','Como mapa obrigatório'],0),
  E('e8','⚫','Carvão e linhas negras','Tecnologia do pigmento','Traços escuros podem resultar do uso de carvão vegetal ou minerais ricos em manganês. A composição precisa depende de análise físico-química.','Material: carvão vegetal ou óxidos de manganês|Aplicação: desenho direto, pincel ou fricção|Diagnóstico: microscopia e espectrometria|Risco: contaminação por fuligem posterior','Nem todo escurecimento na parede é pintura: depósitos de fuligem, minerais e alterações naturais precisam ser separados de traços intencionais.','Ajuda a compreender que estudar arte rupestre também envolve química, geologia e conservação.',REAL.lascaux,'O que pode ser confundido com pigmento preto?',['Fuligem e depósitos naturais','Sombras digitais apenas','Areia branca'],0)
 ]},
 {id:'animais',title:'Galeria dos Animais',image:'assets/scenes_v9/05_animais.jpg',sound:'ambiente amplo e eco profundo',e:[
  E('e9','🐎','Cavalos em movimento','Paleolítico Superior','Cavalos são um dos motivos mais recorrentes em grandes conjuntos paleolíticos europeus. Linhas dorsais, crinas e pernas sugerem direção e movimento.','Técnica: desenho linear e preenchimento|Pigmentos: carvão + ocre|Composição: sobreposição de indivíduos|Estilo: perfil lateral predominante','Sequências de cavalos podem ter sido executadas em momentos diferentes. A análise distingue ordem de traços, diferenças de pigmento e relações de sobreposição.','Mostra domínio de observação animal e planejamento compositivo.',REAL.lascaux,'Qual sítio é conhecido por grandes representações de cavalos?',['Lascaux','Pompeia','Atenas clássica'],0),
  E('e10','🦬','Bisão policromo','Paleolítico Superior','Alguns painéis combinam preto, vermelho e tons naturais da pedra para criar figuras de grande impacto visual.','Técnica: contorno, modelagem cromática e relevo|Pigmentos: carvão/manganês + óxidos de ferro|Superfície: teto ou parede irregular|Efeito: volume e contraste','A policromia pode resultar de mais de uma matéria-prima e de diferentes etapas de aplicação. A superfície da rocha participa da imagem, não é apenas fundo passivo.','Ajuda a discutir planejamento, escolha de materiais e integração entre imagem e geologia.',REAL.altamira,'O que significa policromia?',['Uso de mais de uma cor ou tonalidade','Uso apenas de preto','Pintura feita em papel'],0)
 ]},
 {id:'fogo',title:'Câmara Profunda do Fogo',image:'assets/scenes_v9/06_fogo.jpg',sound:'fogo baixo e reverberação ampla',e:[
  E('e11','🔥','Vestígios de fogo','Arqueologia do cotidiano','Fogueiras arqueológicas podem deixar carvão, cinzas, sedimentos rubefatos, ossos queimados e alterações térmicas no solo.','Vestígios: carvão, cinza e sedimento queimado|Análise: micromorfologia e arqueobotânica|Datação: radiocarbono quando há material adequado|Funções: luz, calor, preparo e sociabilidade','Uma fogueira reconstruída visualmente não prova que todas as cavernas pintadas foram habitadas. Arte e ocupação doméstica podem ocorrer em áreas distintas.','Ajuda a compreender como arqueólogos usam vestígios materiais para reconstruir atividades, e não apenas imagens.',null,'Qual vestígio pode ser associado a uma fogueira antiga?',['Carvão e sedimento queimado','Plástico derretido','Concreto armado'],0),
  E('e12','🪨','Relevo natural como parte da imagem','Tecnologia visual','Saliências, fissuras e curvas da rocha podem ser incorporadas ao corpo de animais ou à organização do painel.','Recurso: topografia da parede|Técnica: adaptação do desenho ao suporte|Documentação: luz rasante e escaneamento 3D|Conservação: controle de microclima','O suporte não é neutro. Em muitos painéis, a forma da parede participa da composição e pode orientar a posição, o tamanho e o contorno das figuras.','Ajuda a compreender a arte rupestre como interação entre gesto, pigmento e superfície geológica.',REAL.altamira,'Qual ferramenta atual ajuda a registrar o relevo da parede?',['Escaneamento 3D','Máquina de escrever','Telégrafo'],0)
 ]},
 {id:'simbolos',title:'Galeria Simbólica',image:'assets/scenes_v9/07_simbolos.jpg',sound:'eco suave e pingos espaçados',e:[
  E('e13','🌀','Círculos, alvos e espirais','Sinais não figurativos','Formas circulares e concêntricas criam centros visuais fortes e podem coexistir com animais, humanos e outros sinais.','Forma: círculos concêntricos/espirais|Técnica: traço contínuo|Pigmento: ocre vermelho ou marrom|Método: descrição morfológica comparativa','Nomes como “sol”, “alvo” ou “espiral” descrevem aparência, não necessariamente significado. A interpretação depende da associação com outros motivos e da tradição regional.','Ajuda a separar descrição visual de interpretação cultural, uma distinção central no trabalho arqueológico.',null,'Ao chamar um sinal de “sol”, o arqueólogo está afirmando seu significado?',['Não; pode ser apenas uma descrição visual','Sim, sempre','Somente se estiver pintado de amarelo'],0),
  E('e14','🐟','Peixes e aves','Fauna e paisagem','Motivos de peixes e aves ampliam o repertório visual para ambientes aquáticos e aéreos.','Categoria: zoomorfos|Técnica: contorno ou silhueta|Contexto: paisagem e recursos locais|Leitura: identificação anatômica cuidadosa','A presença de um animal não implica automaticamente consumo. Ele pode ter importância econômica, ritual, territorial ou simbólica.','Ajuda a relacionar a arte às paisagens conhecidas pelos grupos humanos.',REAL.serra,'A presença de um peixe prova que ele era alimento principal?',['Não necessariamente','Sim, obrigatoriamente','Prova agricultura'],0)
 ]},
 {id:'neolitico',title:'Galeria da Transição Neolítica',image:'assets/scenes_v9/08_neolitico.jpg',sound:'ambiente mais aberto e fogo distante',e:[
  E('e15','🌾','Plantas e produção de alimentos','Neolítico','Em diferentes regiões do mundo, a domesticação de plantas e animais transformou formas de mobilidade, alimentação e organização social.','Processo: gradual e regionalmente variável|Indicadores: sementes, pólen, fitólitos e ferramentas|Economia: cultivo combinado a coleta e caça em muitos contextos|Cronologia: diferente conforme a região','O “Neolítico” não começou no mesmo momento em todo o planeta e não representa uma mudança instantânea. A arqueologia trabalha com processos regionais e longas transições.','Ajuda a comparar sociedades móveis e estratégias de produção de alimentos sem criar uma falsa linha evolutiva única.',null,'A agricultura surgiu ao mesmo tempo em todo o mundo?',['Não; ocorreu em momentos e regiões diferentes','Sim, no mesmo ano','Somente na Europa'],0),
  E('e16','🏺','Cerâmica e recipientes','Neolítico e Holoceno','Recipientes cerâmicos permitem armazenar, transportar e preparar alimentos, mas sua presença e cronologia variam entre regiões.','Matéria-prima: argila + tempero mineral/vegetal|Produção: modelagem, secagem e queima|Análise: pasta, forma, superfície e resíduos|Uso: armazenamento e preparo, entre outras funções','Fragmentos cerâmicos são estudados por tecnologia, decoração, marcas de uso e resíduos. Um vaso desenhado em painel não substitui o estudo dos objetos arqueológicos reais.','Ajuda a discutir tecnologias associadas a novas formas de armazenamento e preparo.',null,'O que arqueólogos analisam em fragmentos cerâmicos?',['Pasta, forma, superfície e resíduos','Somente a cor','Somente o peso'],0)
 ]},
 {id:'atelie',title:'Ateliê Rupestre',image:'assets/scenes_v9/09_atelie.jpg',sound:'silêncio profundo e eco suave',e:[
  E('e17','🎨','Pigmentos minerais','Tecnologia da pintura','Ocres ricos em óxidos de ferro produzem vermelhos, amarelos e castanhos. Carvão e manganês podem gerar tons escuros.','Preparação: moagem e mistura|Aplicação: dedo, pincel simples, sopro ou fricção|Aglutinantes: variáveis e nem sempre preservados|Análise: espectrometria, microscopia e mineralogia','A aparência visual não basta para identificar a composição química. A mesma cor pode resultar de diferentes minerais e processos de alteração.','Ajuda a compreender a pintura rupestre como tecnologia de materiais, além de expressão gráfica.',null,'Qual material pode produzir tons vermelhos?',['Óxidos de ferro','Alumínio polido','Vidro transparente'],0),
  E('e18','🧑‍🎨','Sua interpretação visual','Atividade final','Depois de observar técnicas e motivos, você pode criar uma composição própria inspirada no repertório estudado. Ela é uma atividade contemporânea de aprendizagem, não uma reprodução arqueológica autêntica.','Ferramentas: pincel digital e carimbos|Cores: paleta inspirada em ocres|Suporte: parede virtual|Objetivo: síntese criativa do conteúdo','Produzir a própria imagem ajuda a perceber escolhas de forma, escala, repetição, composição e cor. O exercício também reforça a diferença entre reconstrução didática e vestígio arqueológico real.','Ajuda a transformar observação passiva em produção ativa e reflexão sobre técnica.',null,'Sua arte criada no aplicativo é um vestígio arqueológico real?',['Não; é uma atividade educativa contemporânea','Sim, automaticamente','Somente se usar vermelho'],0)
 ]}
];
const order=scenes.map(s=>s.id), total=scenes.reduce((n,s)=>n+s.e.length,0), $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const intro=$('#intro'),game=$('#game'),viewer=$('#viewer'),track=$('#track'),hotspots=$('#hotspots'),panel=$('#infoPanel'),panos=$$('.pano');
let si=0,yaw=0,pitch=0,hfov=96,pw=0,ph=0,ppd=0,cx=0,cy=0,drag=false,lx=0,ly=0,current=null,torch=false,sound=false,audioCtx=null,ambient=[],deferredPrompt=null,tool='brush',drawing=false,last={x:0,y:0},artDone=false;
const found=new Set(),passed=new Set(),visited=new Set(['entrada']);
function scene(){return scenes[si]} function norm(a){return((a+180)%360+360)%360-180} function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function save(){localStorage.setItem('cav_game_v9',JSON.stringify({si,yaw,pitch,hfov,found:[...found],passed:[...passed],visited:[...visited],artDone}))}
function load(){try{let d=JSON.parse(localStorage.getItem('cav_game_v9')||'{}');if(Number.isInteger(d.si)&&scenes[d.si])si=d.si;if(typeof d.yaw==='number')yaw=d.yaw;if(typeof d.pitch==='number')pitch=d.pitch;if(typeof d.hfov==='number')hfov=d.hfov;(d.found||[]).forEach(x=>found.add(x));(d.passed||[]).forEach(x=>passed.add(x));(d.visited||[]).forEach(x=>visited.add(x));artDone=!!d.artDone}catch(e){}}
function layout(){let w=viewer.clientWidth,h=viewer.clientHeight;ppd=w/hfov;pw=ppd*360;ph=pw/2;cx=w/2-pw/2;cy=h/2-ph/2;panos.forEach((im,i)=>{im.style.width=pw+'px';im.style.height=ph+'px';im.style.left=((i-1)*pw)+'px';im.style.top=0});render()}
function render(){track.style.width=pw+'px';track.style.height=ph+'px';track.style.transform=`translate3d(${cx-yaw/360*pw}px,${cy+pitch/180*ph}px,0)`;renderSpots();$('#needle').style.transform=`rotate(${-yaw}deg)`;$('#heading').textContent=Math.round((yaw+360)%360)+'°'}
function proj(h){let d=norm(h.yaw-yaw),vf=viewer.clientHeight/ppd;if(Math.abs(d)>hfov*.6||Math.abs(h.pitch-pitch)>vf*.68)return null;return{x:viewer.clientWidth/2+d*ppd,y:viewer.clientHeight/2-(h.pitch-pitch)*ppd}}
function hotspotData(){let ev=scene().e.map((e,i)=>({...e,type:'info',yaw:[-125,82][i%2],pitch:[10,8][i%2]}));if(si>0)ev.push({id:'back',type:'nav',yaw:178,pitch:-5,label:'Voltar',dir:-1});if(si<scenes.length-1)ev.push({id:'next',type:'nav',yaw:0,pitch:-6,label:'Avançar',dir:1});return ev}
function buildSpots(){hotspots.innerHTML='';hotspotData().forEach(h=>{let d=document.createElement('div');d.className='spot '+(h.type==='nav'?'nav':'')+(found.has(h.id)?' done':'');d.dataset.id=h.id;d.innerHTML=`<button aria-label="${h.type==='nav'?h.label:h.title}"></button><label>${h.type==='nav'?h.label:h.title}</label>`;d.querySelector('button').onclick=e=>{e.stopPropagation();h.type==='nav'?walk(h.dir):openEvidence(h)};hotspots.appendChild(d)});renderSpots()}
function renderSpots(){$$('.spot').forEach(el=>{let h=hotspotData().find(x=>x.id===el.dataset.id);if(!h)return;let p=proj(h);el.style.opacity=p?1:0;el.style.pointerEvents=p?'auto':'none';if(p){el.style.left=p.x+'px';el.style.top=p.y+'px'}el.classList.toggle('done',found.has(h.id))})}
function setScene(){let s=scene();panos.forEach(p=>{p.src=s.image;p.dataset.scene=s.id});visited.add(s.id);buildSpots();updateMission();setAmbientLabel();buildMapHud();buildSceneRail();save();layout()}
function preloadScene(src){return new Promise((resolve,reject)=>{let im=new Image();im.onload=()=>resolve();im.onerror=reject;im.src=src})}
async function gotoScene(index,source='map'){if(!Number.isInteger(index)||!scenes[index]||index===si)return;let target=scenes[index];$('#transitionText').textContent=`Carregando ${target.title}...`;$('#transition').classList.remove('hidden');track.style.transition='transform .32s ease,filter .32s';track.style.filter='blur(2px) brightness(.58)';try{await preloadScene(target.image);si=index;yaw=0;pitch=0;hfov=96;setScene();panel.classList.remove('open');toast(`${target.title} carregada`)}catch(err){console.error('Falha ao carregar ambiente',target.image,err);toast('Não foi possível carregar este ambiente.')}finally{track.style.filter='';setTimeout(()=>{track.style.transition='none';$('#transition').classList.add('hidden')},220)}}
function walk(dir){let ni=clamp(si+dir,0,scenes.length-1);if(ni===si)return;gotoScene(ni,dir>0?'next':'back')}
function rotate(d){yaw=norm(yaw+d);render();save()}
viewer.onpointerdown=e=>{drag=true;lx=e.clientX;ly=e.clientY;viewer.setPointerCapture?.(e.pointerId)};viewer.onpointermove=e=>{let r=viewer.getBoundingClientRect();$('#torch').style.setProperty('--x',((e.clientX-r.left)/r.width*100)+'%');$('#torch').style.setProperty('--y',((e.clientY-r.top)/r.height*100)+'%');if(!drag)return;let dx=e.clientX-lx,dy=e.clientY-ly;yaw=norm(yaw-dx/ppd);pitch=clamp(pitch+dy/ppd,-55,55);lx=e.clientX;ly=e.clientY;render()};['pointerup','pointercancel','pointerleave'].forEach(k=>viewer.addEventListener(k,()=>drag=false));viewer.onwheel=e=>{e.preventDefault();hfov=clamp(hfov+e.deltaY*.035,55,118);layout();save()};
window.onkeydown=e=>{if(!game.classList.contains('show')||!$('#modal').classList.contains('hidden')||!$('#atelier').classList.contains('hidden'))return;let k=e.key.toLowerCase();if(k==='w'||e.key==='ArrowUp')walk(1);if(k==='s'||e.key==='ArrowDown')walk(-1);if(k==='a'||e.key==='ArrowLeft')rotate(-12);if(k==='d'||e.key==='ArrowRight')rotate(12)};$$('.walk-pad button').forEach(b=>b.onclick=()=>({w:()=>walk(1),s:()=>walk(-1),a:()=>rotate(-15),d:()=>rotate(15)})[b.dataset.key]());
function openEvidence(h){current=h;yaw=h.yaw;pitch=h.pitch;hfov=70;layout();setTimeout(()=>{fillPanel(h);panel.classList.add('open')},180)}
function fillPanel(h){$('#evIcon').textContent=h.icon;$('#evPeriod').textContent=h.period;$('#evTitle').textContent=h.title;$('#evIntro').textContent=h.intro;$('#panelHero').style.backgroundImage=`linear-gradient(to top,rgba(0,0,0,.18),transparent),url('${scene().image}')`;$('#tech').innerHTML=h.tech.split('|').map(x=>{let [a,...b]=x.split(':');return `<div class="tech-card"><small>${a}</small>${b.join(':')}</div>`}).join('');$('#evAnalysis').textContent=h.analysis;$('#evMeaning').textContent=h.meaning;let real=h.ref;$('#compare').innerHTML=`<figure><img src="${scene().image}"><figcaption>Nossa reconstrução — ${scene().title}</figcaption></figure>${real?`<figure><img src="${real.img}" onerror="this.style.display='none'"><figcaption><b>Referência real</b><br>${real.name}<br><span>${real.credit}</span></figcaption></figure>`:`<figure><div style="height:90px;display:grid;place-items:center;color:#bfa98e;padding:10px;text-align:center">Referência didática sem fotografia externa.</div><figcaption>Comparação arqueológica</figcaption></figure>`}`;renderQuiz(h);updateReg()}
function renderQuiz(h){let area=$('#miniQuiz');area.innerHTML=`<div class="quiz-options">${h.opts.map((o,i)=>`<button data-i="${i}">${o}</button>`).join('')}</div><p class="box" id="quizMsg">${passed.has(h.id)?'Teste concluído. Você pode registrar a evidência.':'Escolha uma resposta.'}</p>`;area.querySelectorAll('button').forEach(b=>{if(passed.has(h.id)||found.has(h.id))b.disabled=true;b.onclick=()=>{let i=+b.dataset.i,all=[...area.querySelectorAll('button')];all.forEach(x=>x.disabled=true);if(i===h.correct){b.classList.add('correct');passed.add(h.id);$('#quizMsg').innerHTML='<b>Correto.</b> A evidência pode ser registrada no caderno.'}else{b.classList.add('wrong');all[h.correct].classList.add('correct');$('#quizMsg').innerHTML='<b>Resposta incorreta.</b> Observe a alternativa destacada e releia a ficha.'}updateReg();save()}})}
function updateReg(){let b=$('#registerBtn');if(found.has(current.id)){b.disabled=true;b.textContent='✓ Evidência registrada'}else if(passed.has(current.id)){b.disabled=false;b.textContent='✓ Registrar no caderno de campo'}else{b.disabled=true;b.textContent='Responder ao teste para registrar'}}
$('#registerBtn').onclick=()=>{if(!current||!passed.has(current.id)||found.has(current.id))return;found.add(current.id);updateReg();buildSpots();updateMission();toast('+100 pontos • Evidência registrada');save();checkComplete()};$('#closePanel').onclick=()=>panel.classList.remove('open');
$('#zoomBtn').onclick=()=>{hfov=55;yaw=current.yaw;pitch=current.pitch;layout();toast('Zoom arqueológico ativado')};
$('#narrateBtn').onclick=()=>{speechSynthesis.cancel();let t=new SpeechSynthesisUtterance(`${current.title}. ${current.intro}. ${current.analysis}. ${current.meaning}`);t.lang='pt-BR';t.rate=.92;speechSynthesis.speak(t)};
function updateMission(){let mp=$('#mapProgress');if(mp)mp.style.width=(visited.size/scenes.length*100)+'%';let mv=$('#mapVisited');if(mv)mv.textContent=`${visited.size}/${scenes.length}`;let me=$('#mapEvidence');if(me)me.textContent=`${found.size}/${total}`;}
function toast(t){let e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
function showModal(html){$('#modalBody').innerHTML=html;$('#modal').classList.remove('hidden')}$('#modalClose').onclick=()=>$('#modal').classList.add('hidden');
function mapHtml(){return `<h2>🗺️ Mapa da Caverna</h2><p>Os ambientes visitados ficam destacados. Clique em uma galeria para viajar diretamente até ela.</p><div class="map-grid">${scenes.map((s,i)=>`<button class="map-node ${visited.has(s.id)?'visited':''} ${i===si?'current':''}" data-i="${i}"><b>${i+1}. ${s.title}</b><br><small>${visited.has(s.id)?'Visitado':'Não visitado'}</small></button>`).join('')}</div><p><small>Para maior imersão, use W/S ou ↑/↓ durante a exploração em vez do salto pelo mapa.</small></p>`}
$('#mapBtn').onclick=()=>{$('#leftMap').classList.toggle('map-hidden')};
$('#timelineBtn').onclick=()=>showModal(`<h2>⌛ Linha do Tempo da Pré-História</h2><div class="timeline"><div class="time-card"><b>Paleolítico Inferior</b><br><small>Ferramentas de pedra, mobilidade e longa história evolutiva humana. As cronologias variam regionalmente.</small></div><div class="time-card"><b>Paleolítico Superior</b><br><small>Na Europa, florescem grandes conjuntos de arte parietal entre dezenas de milhares de anos atrás e o fim do Pleistoceno.</small></div><div class="time-card"><b>Transição para o Holoceno</b><br><small>Mudanças climáticas, novas paisagens e diferentes estratégias de subsistência.</small></div><div class="time-card"><b>Neolítico</b><br><small>Em várias regiões, agricultura, domesticação, maior sedentarização, cerâmica e novas formas de organização social — em cronologias diferentes.</small></div></div><p class="box"><b>Importante:</b> Paleolítico e Neolítico são grandes categorias arqueológicas. Elas não representam uma evolução única e simultânea para todos os povos.</p>`);
function journalHtml(){let evid=scenes.flatMap(s=>s.e);return `<h2>📓 Caderno de Campo</h2><p>Seu registro é salvo automaticamente neste aparelho.</p><div class="journal-list">${evid.map(e=>`<div class="journal-item ${found.has(e.id)?'done':''}"><span>${found.has(e.id)?'✅':'⬜'}</span><div><b>${e.title}</b><br><small>${found.has(e.id)?'Evidência registrada':'Ainda não registrada'}</small></div></div>`).join('')}</div><div class="box"><b>Galerias visitadas:</b> ${visited.size}/${scenes.length}<br><b>Arte própria:</b> ${artDone?'concluída':'pendente'}</div>`}
$('#journalBtn').onclick=()=>showModal(journalHtml());
$('#helpBtn').onclick=()=>showModal(`<h2>Como explorar</h2><ul><li><b>W/S ou ↑/↓:</b> caminhar para a próxima/galeria anterior.</li><li><b>A/D ou ←/→:</b> girar a visão.</li><li><b>Mouse/toque:</b> arrastar livremente em 360°.</li><li><b>Roda do mouse:</b> zoom.</li><li><b>Pontos dourados:</b> evidências arqueológicas.</li><li><b>Pontos azuis:</b> passagens entre ambientes.</li><li><b>Lanterna:</b> escurece o entorno e destaca a área observada.</li></ul><p>A última galeria abre o Ateliê Rupestre.</p>`);
$('#torchBtn').onclick=()=>{torch=!torch;$('#torch').classList.toggle('on',torch);$('#torchBtn').textContent=torch?'🔥 Lanterna ativa':'🔦 Lanterna'};
function setAmbientLabel(){}
function startSound(){audioCtx=new (window.AudioContext||window.webkitAudioContext)();let m=audioCtx.createGain();m.gain.value=.035;m.connect(audioCtx.destination);let o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='sine';o.frequency.value=42+si*2;g.gain.value=.15;o.connect(g).connect(m);o.start();let b=audioCtx.createBuffer(1,audioCtx.sampleRate*2,audioCtx.sampleRate),d=b.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=(Math.random()*2-1)*.12;let n=audioCtx.createBufferSource(),ng=audioCtx.createGain();n.buffer=b;n.loop=true;ng.gain.value=.2;n.connect(ng).connect(m);n.start();ambient=[o,n,m]}
function stopSound(){ambient.forEach(n=>{try{n.stop&&n.stop()}catch(e){}});audioCtx?.close();audioCtx=null;ambient=[]}$('#soundBtn').onclick=()=>{sound=!sound;sound?startSound():stopSound();$('#soundBtn').textContent=sound?'🔇 Silenciar':'🔊 Som'};
function openAtelier(){panel.classList.remove('open');$('#atelier').classList.remove('hidden');initCanvas()}$('#atelierClose').onclick=()=>$('#atelier').classList.add('hidden');
const canvas=$('#artCanvas'),ctx=canvas.getContext('2d');function paintBase(){ctx.fillStyle='#c49a6c';ctx.fillRect(0,0,canvas.width,canvas.height);for(let i=0;i<700;i++){let a=Math.random()*.06;ctx.fillStyle=`rgba(80,45,25,${a})`;ctx.fillRect(Math.random()*canvas.width,Math.random()*canvas.height,1+Math.random()*4,1+Math.random()*3)}}function initCanvas(){if(canvas.dataset.init)return;canvas.dataset.init=1;paintBase()}function cp(e){let r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)/r.width*canvas.width,y:(e.clientY-r.top)/r.height*canvas.height}}
function drawStamp(x,y){ctx.save();ctx.translate(x,y);ctx.strokeStyle=$('#paintColor').value;ctx.fillStyle=$('#paintColor').value;ctx.lineWidth=7;ctx.lineCap='round';if(tool==='hand'){ctx.beginPath();ctx.arc(0,18,22,0,Math.PI*2);ctx.fill();[-28,-14,0,14,28].forEach((dx,i)=>{ctx.beginPath();ctx.moveTo(dx*.55,5);ctx.lineTo(dx*.78,-38-Math.abs(i-2)*3);ctx.stroke()})}if(tool==='animal'){ctx.beginPath();ctx.ellipse(0,0,55,28,0,0,Math.PI*2);ctx.fill();ctx.fillRect(43,-6,35,10);ctx.beginPath();ctx.moveTo(70,-5);ctx.lineTo(84,-25);ctx.moveTo(70,-2);ctx.lineTo(88,8);ctx.moveTo(-30,20);ctx.lineTo(-38,52);ctx.moveTo(28,20);ctx.lineTo(34,52);ctx.stroke()}if(tool==='human'){ctx.beginPath();ctx.arc(0,-35,10,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.moveTo(0,-25);ctx.lineTo(0,25);ctx.moveTo(0,-5);ctx.lineTo(-28,12);ctx.moveTo(0,-5);ctx.lineTo(34,-18);ctx.moveTo(0,25);ctx.lineTo(-22,55);ctx.moveTo(0,25);ctx.lineTo(22,55);ctx.stroke()}if(tool==='spiral'){ctx.beginPath();for(let a=0;a<Math.PI*5;a+=.1){let r=a*4;let X=Math.cos(a)*r,Y=Math.sin(a)*r;a===0?ctx.moveTo(X,Y):ctx.lineTo(X,Y)}ctx.stroke()}ctx.restore()}
canvas.onpointerdown=e=>{let p=cp(e);if(tool==='brush'){drawing=true;last=p}else drawStamp(p.x,p.y);canvas.setPointerCapture?.(e.pointerId)};canvas.onpointermove=e=>{if(!drawing||tool!=='brush')return;let p=cp(e);ctx.strokeStyle=$('#paintColor').value;ctx.lineWidth=$('#paintSize').value;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(last.x,last.y);ctx.lineTo(p.x,p.y);ctx.stroke();last=p};canvas.onpointerup=()=>drawing=false;$$('.atelier-tools [data-tool]').forEach(b=>b.onclick=()=>{$$('.atelier-tools [data-tool]').forEach(x=>x.classList.remove('active'));b.classList.add('active');tool=b.dataset.tool});$('#clearArt').onclick=()=>paintBase();$('#saveArt').onclick=()=>{let a=document.createElement('a');a.download='minha-arte-rupestre-sesiverso-2026.png';a.href=canvas.toDataURL('image/png');a.click()};$('#completeArt').onclick=()=>{artDone=true;save();toast('Atividade artística concluída');$('#atelier').classList.add('hidden');checkComplete()};
function checkComplete(){if(found.size===total&&visited.size===scenes.length&&artDone){$('#score').textContent=(found.size*100+visited.size*50+500)+' pontos';$('#celebration').classList.remove('hidden');confetti()}}
function confetti(){let c=$('#confetti'),x=c.getContext('2d');c.width=innerWidth;c.height=innerHeight;let p=Array.from({length:100},()=>({x:Math.random()*c.width,y:-Math.random()*c.height,v:2+Math.random()*5,r:3+Math.random()*6,a:Math.random()*6.2}));let f=0;(function r(){x.clearRect(0,0,c.width,c.height);p.forEach(o=>{o.y+=o.v;o.x+=Math.sin(o.a+f*.03);x.save();x.translate(o.x,o.y);x.rotate(o.a+f*.04);x.fillStyle=`hsl(${20+Math.random()*45} 80% 60%)`;x.fillRect(-o.r,-o.r/2,o.r*2,o.r);x.restore()});if(++f<220)requestAnimationFrame(r)})()}
$('#keepExploring').onclick=()=>$('#celebration').classList.add('hidden');$('#finalQuiz').onclick=()=>{ $('#celebration').classList.add('hidden');showModal(`<h2>🧠 Quiz final</h2><p>Você já respondeu aos testes de campo. Revisão final:</p><div class="box"><b>1.</b> Pigmentos vermelhos frequentemente estão associados a óxidos de ferro.</div><div class="box"><b>2.</b> Nem toda figura animal é automaticamente uma “cena de caça”.</div><div class="box"><b>3.</b> Sinais abstratos exigem descrição e contexto antes da interpretação.</div><div class="box"><b>4.</b> O Neolítico ocorreu em cronologias diferentes conforme a região.</div><p><b>Conclusão:</b> arqueologia trabalha com evidências, comparação e hipóteses — não com certezas automáticas a partir de uma imagem isolada.</p>`)};
$('#enter').onclick=()=>{intro.classList.remove('show');game.classList.add('show');setScene();setTimeout(()=>{let first=hotspotData().find(h=>h.type==='info');if(first)openEvidence(first)},650)};$('#how').onclick=()=>{intro.classList.remove('show');game.classList.add('show');setScene();$('#helpBtn').click()};

const MAP_POS=[
  [16,86],[30,76],[45,66],[57,54],[70,43],[80,30],[68,18],[48,26],[32,36]
];
function shortSceneTitle(t){return t.replace('Entrada da Caverna','Entrada').replace('Corredor dos Vestígios','Corredor').replace('Galeria das Mãos','Galeria das Mãos').replace('Passagem Estreita','Passagem Estreita').replace('Galeria dos Animais','Galeria dos Animais').replace('Galeria de Caça','Galeria da Caça').replace('Câmara do Fogo','Câmara Profunda').replace('Transição Neolítica','Galeria Simbólica').replace('Ateliê Rupestre','Ateliê Rupestre')}
function buildMapHud(){
  const host=$('#mapNodes'); if(!host)return; host.innerHTML='';
  scenes.forEach((s,i)=>{
    const [x,y]=MAP_POS[i]||[50,50];
    const dot=document.createElement('button'); dot.className='map-node-dot'+(visited.has(s.id)?' visited':'')+(i===si?' current':''); dot.style.left=x+'%'; dot.style.top=y+'%'; dot.title=s.title; dot.onclick=()=>gotoScene(i,'map'); host.appendChild(dot);
    const lab=document.createElement('div');lab.className='map-label';lab.textContent=shortSceneTitle(s.title);lab.style.left=(x+(x<50?7:-2))+'%';lab.style.top=(y-5)+'%';if(x>58)lab.style.transform='translateX(-90%)';host.appendChild(lab);
    if(i===si){const tag=document.createElement('div');tag.className='you-are-here';tag.textContent='Você está aqui';tag.style.left=Math.min(72,x+8)+'%';tag.style.top=Math.min(88,y+7)+'%';host.appendChild(tag)}
  });
}
function buildSceneRail(){
  const rail=$('#sceneRail'); if(!rail)return; rail.innerHTML='';
  scenes.forEach((s,i)=>{const b=document.createElement('button');b.className='scene-thumb'+(i===si?' active':'')+(visited.has(s.id)?' visited':'');b.innerHTML=`<img src="${s.image}" alt=""><span>${i+1}. ${shortSceneTitle(s.title)}</span>`;b.onclick=()=>gotoScene(i,'rail');rail.appendChild(b)});
  const active=rail.querySelector('.active'); active?.scrollIntoView({inline:'center',block:'nearest'});
}
$('#prevScene').onclick=()=>walk(-1);$('#nextScene').onclick=()=>walk(1);
const FULL_QUIZ=[
{q:'Qual técnica produz uma mão em negativo?',o:['Pigmento pulverizado ao redor da mão','Incisão com ferramenta metálica','Modelagem em argila','Impressão tipográfica'],a:0},
{q:'Qual material está frequentemente associado a pigmentos vermelhos rupestres?',o:['Óxidos de ferro como hematita','Sal refinado','Alumínio metálico','Gesso industrial'],a:0},
{q:'Ao interpretar um animal pintado, qual postura é mais adequada?',o:['Considerar contexto, estilo e associação com outros motivos','Assumir sempre que é uma cena de caça','Identificar qualquer animal como doméstico','Ignorar o suporte rochoso'],a:0},
{q:'O que a superposição de figuras pode ajudar a analisar?',o:['A sequência relativa de execução','A temperatura exata do dia da pintura','O nome do artista','A língua falada pelo grupo'],a:0},
{q:'Qual aspecto do suporte pode ser explorado pelo artista rupestre?',o:['Saliências e relevos naturais da rocha','Apenas superfícies perfeitamente planas','Somente paredes artificiais','Exclusivamente madeira'],a:0},
{q:'Por que sinais abstratos devem ser interpretados com cautela?',o:['Porque seu significado depende do contexto arqueológico','Porque não são produzidos por humanos','Porque são sempre modernos','Porque não podem ser documentados'],a:0},
{q:'Qual elemento ajuda a reconhecer cervídeos em muitos painéis?',o:['Galhadas ramificadas','Nadadeiras','Bico curvo','Carapaça'],a:0},
{q:'O que caracteriza uma cena narrativa rupestre?',o:['Interação e ação entre figuras','Uso obrigatório de escrita','Perspectiva fotográfica','Presença de moldura'],a:0},
{q:'No Neolítico, qual transformação ocorreu em várias regiões?',o:['Expansão da agricultura e maior sedentarização','Invenção da eletricidade','Uso de motores','Impressão industrial'],a:0},
{q:'O carvão vegetal pode ser usado em arte rupestre principalmente para produzir qual tonalidade?',o:['Preto','Azul intenso','Verde fluorescente','Prata'],a:0},
{q:'Qual é uma função da arqueometria no estudo da arte rupestre?',o:['Analisar composição de pigmentos e materiais','Traduzir automaticamente símbolos','Descobrir nomes próprios dos autores','Determinar crenças com certeza absoluta'],a:0},
{q:'Por que uma reconstrução digital deve ser identificada como reconstrução?',o:['Para não confundi-la com o registro arqueológico original','Porque reconstruções não têm valor educativo','Porque imagens digitais não podem ser usadas em museus','Porque toda reconstrução é historicamente falsa'],a:0}
];
function openFullQuiz(){let score=0,answered=0;showModal(`<h2>🧠 Quiz da Pré-História</h2><p>Responda às 12 questões sobre arte rupestre, arqueologia, Paleolítico e Neolítico.</p>`+FULL_QUIZ.map((x,i)=>`<div class="quiz-block"><b>${i+1}. ${x.q}</b><div class="quiz-options">${x.o.map((v,j)=>`<button data-q="${i}" data-a="${j}">${v}</button>`).join('')}</div></div>`).join('')+`<div id="fullQuizResult" class="box">Respondidas: 0/12</div>`);document.querySelectorAll('#modalBody .quiz-options button').forEach(b=>b.onclick=()=>{const qi=+b.dataset.q,ai=+b.dataset.a,g=b.parentElement;if(g.dataset.done)return;g.dataset.done='1';answered++;if(ai===FULL_QUIZ[qi].a){b.classList.add('correct');score++}else{b.classList.add('wrong');g.children[FULL_QUIZ[qi].a].classList.add('correct')}Array.from(g.children).forEach(x=>x.disabled=true);$('#fullQuizResult').innerHTML=answered===12?`<b>Resultado: ${score}/12</b><br>${score>=10?'Excelente domínio do conteúdo.':score>=7?'Bom resultado. Revise as fichas arqueológicas para avançar ainda mais.':'Continue explorando as galerias e consulte as fichas antes de tentar novamente.'}`:`Respondidas: ${answered}/12 • Acertos: ${score}`})}
$('#quizTopBtn').onclick=openFullQuiz;
$('#drawBtn').onclick=openAtelier;

window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').classList.remove('hidden')});$('#installBtn').onclick=async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('#installBtn').classList.add('hidden')};if('serviceWorker'in navigator&&location.protocol!=='file:')window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js?v=9',{updateViaCache:'none'}).then(r=>r.update()).catch(()=>{}));window.addEventListener('resize',layout);load();updateMission();buildMapHud();buildSceneRail();
